
# annotyacctab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'|{\x96<\xc74\xb4\xc0\xc2_Z#A\x81\xe0\x0f'
    
_lr_action_items = {'TYPE':([8,14,19,21,22,23,],[12,12,-12,-13,-14,-11,]),'$end':([0,3,4,5,6,7,8,10,11,13,14,15,19,20,21,22,23,],[-15,-3,-4,-6,0,-9,-15,-8,-10,-1,-5,-2,-12,-7,-13,-14,-11,]),'VAL':([12,16,17,],[19,21,22,]),'FILENAME':([0,1,5,8,11,13,14,15,19,20,21,22,23,],[2,2,2,-15,-10,-1,-5,-2,-12,-7,-13,-14,-11,]),'IDENT':([8,14,19,21,22,23,],[16,16,-12,-13,-14,-11,]),'CALL':([8,14,19,21,22,23,],[17,17,-12,-13,-14,-11,]),'NUMBER':([2,9,18,],[9,18,23,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'annotation_string':([8,14,],[15,20,]),'annotation_string_opt':([8,],[11,]),'position':([0,1,5,],[1,8,1,]),'empty':([0,8,],[3,13,]),'annotation':([8,14,],[14,14,]),'block_string':([0,5,],[4,10,]),'block':([0,5,],[5,5,]),'file':([0,],[6,]),'block_string_opt':([0,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('annotation_string_opt -> empty','annotation_string_opt',1,'p_annotation_string_opt','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',41),
  ('annotation_string_opt -> annotation_string','annotation_string_opt',1,'p_annotation_string_opt','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',42),
  ('block_string_opt -> empty','block_string_opt',1,'p_block_string_opt','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',41),
  ('block_string_opt -> block_string','block_string_opt',1,'p_block_string_opt','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',42),
  ('annotation_string -> annotation','annotation_string',1,'p_annotation_string_1','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',54),
  ('block_string -> block','block_string',1,'p_block_string_1','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',54),
  ('annotation_string -> annotation annotation_string','annotation_string',2,'p_annotation_string_2','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',61),
  ('block_string -> block block_string','block_string',2,'p_block_string_2','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\plyparser.py',61),
  ('file -> block_string_opt','file',1,'p_file','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',228),
  ('block -> position position annotation_string_opt','block',3,'p_block','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',233),
  ('position -> FILENAME NUMBER NUMBER NUMBER','position',4,'p_position','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',238),
  ('annotation -> TYPE VAL','annotation',2,'p_annotation_1','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',243),
  ('annotation -> IDENT VAL','annotation',2,'p_annotation_2','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',248),
  ('annotation -> CALL VAL','annotation',2,'p_annotation_3','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',253),
  ('empty -> <empty>','empty',0,'p_empty','C:\\cygwin\\home\\lhhv\\dev\\dev-misc\\sublime\\mlfi\\annotparser.py',258),
]
